# -*- coding: utf-8 -*-
"""NS Final Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UNB8tb9ab_368Er6GCL3J5-1jc0fFUAH
"""

G = nx.read_gml('/path', label=None)
G = nx.graph(G)

"""## Basic Properties and Viz"""

import networkx as nx
import matplotlib.pyplot as plt

# Create a simple graph (Erdős-Rényi for demonstration)
def generate_erdos_renyi(N, avg_k):
    p = avg_k / (N - 1)
    G = nx.erdos_renyi_graph(N, p)
    return G

# 3. Watts-Strogatz (WS) Network
def create_ws_network(n, k, p):
    G = nx.watts_strogatz_graph(n, k, p)  # n: nodes, k: neighbors, p: probability of rewiring
    return G

# 1. Basic Graph Visualization
def visualize_graph(G):
    plt.figure(figsize=(8, 8))
    pos = nx.spring_layout(G)  # Layout for node positioning
    nx.draw(G, pos, with_labels=True, node_color='skyblue', node_size=500, edge_color='gray')
    plt.title('Graph Visualization')
    plt.show()

# 2. Degree Distribution Plot
def plot_degree_distribution(G):
    degrees = [G.degree(n) for n in G.nodes()]
    plt.figure(figsize=(8, 6))
    plt.hist(degrees, bins=range(min(degrees), max(degrees)+1), color='skyblue', edgecolor='black')
    plt.title('Degree Distribution')
    plt.xlabel('Degree')
    plt.ylabel('Frequency')
    plt.show()
    print("\nDegree Distribution (node: degree):")
    degree_dict = {node: G.degree(node) for node in G.nodes()}
    for node, degree in degree_dict.items():
        print(f"Node {node}: {degree}")

# 3. Basic Graph Properties
def graph_properties(G):
    num_nodes = G.number_of_nodes()
    num_edges = G.number_of_edges()
    avg_degree = sum(dict(G.degree()).values()) / num_nodes

    print(f"Number of nodes: {num_nodes}")
    print(f"Number of edges: {num_edges}")
    print(f"Average degree: {avg_degree:.2f}")

    # Clustering Coefficient
    avg_clustering = nx.average_clustering(G)
    print(f"Average clustering coefficient: {avg_clustering:.2f}")

    # Diameter (only for connected graphs)
    if nx.is_connected(G):
        diameter = nx.diameter(G)
        print(f"Diameter: {diameter}")
    else:
        print("Graph is not connected. Cannot compute diameter.")

    # Connected Components
    num_components = nx.number_connected_components(G)
    print(f"Number of connected components: {num_components}")

# 4. Shortest Path Example (between two random nodes)
def shortest_path_example(G):
    if nx.is_connected(G):
        node1, node2 = random.sample(G.nodes(), 2)
        shortest_path = nx.shortest_path(G, source=node1, target=node2)
        print(f"Shortest path between {node1} and {node2}: {shortest_path}")
    else:
        print("Graph is not connected. Cannot compute shortest paths.")

# 5. Centrality Measures (Degree and Betweenness Centrality)
def centrality_measures(G):
    degree_centrality = nx.degree_centrality(G)
    betweenness_centrality = nx.betweenness_centrality(G)

    # Show the top 3 nodes with the highest degree and betweenness centrality
    sorted_degree = sorted(degree_centrality.items(), key=lambda x: x[1], reverse=True)
    sorted_betweenness = sorted(betweenness_centrality.items(), key=lambda x: x[1], reverse=True)

    print("\nTop 3 nodes by Degree Centrality:")
    for node, centrality in sorted_degree[:3]:
        print(f"Node {node}: {centrality:.2f}")

    print("\nTop 3 nodes by Betweenness Centrality:")
    for node, centrality in sorted_betweenness[:3]:
        print(f"Node {node}: {centrality:.2f}")

# Main function to run the analysis
def main():
    G = create_graph()  # Create a random graph
    visualize_graph(G)  # 1. Visualize the graph
    graph_properties(G)  # 2. Print basic properties of the graph
    plot_degree_distribution(G)  # 3. Plot degree distribution
    shortest_path_example(G)  # 4. Show an example of the shortest path
    centrality_measures(G)  # 5. Compute centrality measures

if __name__ == "__main__":
    main()

def average_degree(N, p):
    return p * (N - 1)

def degree_distribution(k, lambda_val):
    return (math.exp(-lambda_val) * lambda_val**k) / math.factorial(k)

lambda_val = average_degree(N, p)
k_values = range(20)  # Calculate for k = 0 to 19
pk_values = [degree_distribution(k, lambda_val) for k in k_values]

"""## Attack Threshold"""

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

# Generate a network with power-law degree distribution (Configuration model)
def generate_powerlaw_network(N, gamma):
    while True:
        degree_sequence = np.random.zipf(gamma, N)
        # Ensure the sum of degrees is even
        if sum(degree_sequence) % 2 == 0:
            break
    G = nx.configuration_model(degree_sequence)
    G = nx.Graph(G)  # Remove multi-edges
    G.remove_edges_from(nx.selfloop_edges(G))  # Remove self-loops
    return G

# Attack the network based on a specific metric and fraction of nodes removed
def attack_network(G, metric, fraction_remove):
    N = len(G)
    num_nodes_to_remove = int(fraction_remove * N)

    if metric == 'degree':
        # Remove nodes with the highest degree
        nodes_sorted_by_metric = sorted(G.degree(), key=lambda x: x[1], reverse=True)
    elif metric == 'clustering':
        # Remove nodes with the highest clustering coefficient
        clustering_coefficients = nx.clustering(G)
        nodes_sorted_by_metric = sorted(clustering_coefficients.items(), key=lambda x: x[1], reverse=True)

    nodes_to_remove = [node for node, value in nodes_sorted_by_metric[:num_nodes_to_remove]]
    G.remove_nodes_from(nodes_to_remove)

    # Check if there are any connected components left
    if len(G) == 0 or len(list(nx.connected_components(G))) == 0:
        return 0  # No components left

    # Get the size of the largest connected component
    largest_cc = max(nx.connected_components(G), key=len)
    return len(largest_cc)

# Visualize the network
def visualize_network(G, title):
    plt.figure(figsize=(10, 10))
    pos = nx.spring_layout(G, seed=42)  # For better layout and consistent positioning
    nx.draw_networkx_nodes(G, pos, node_size=10, node_color='blue')
    nx.draw_networkx_edges(G, pos, alpha=0.3)
    plt.title(title)
    plt.show()

# Run the attack simulation and visualize the network
def conspiracy_simulation(N, gamma):
    fractions_removed = np.linspace(0, 1, 20)  # Fractions of nodes to remove
    G = generate_powerlaw_network(N, gamma)

    # Visualize the original network
    visualize_network(G, "Original Network")

    # Simulate degree-based and clustering coefficient-based attacks
    largest_components_degree = []
    largest_components_clustering = []

    for fraction in fractions_removed:
        G_copy1 = G.copy()
        G_copy2 = G.copy()

        size_giant_degree = attack_network(G_copy1, 'degree', fraction)
        size_giant_clustering = attack_network(G_copy2, 'clustering', fraction)

        largest_components_degree.append(size_giant_degree)
        largest_components_clustering.append(size_giant_clustering)

        # Visualize the network after 20% of nodes have been removed
        if fraction == 0.2:  # Visualizing at 20% removal
            visualize_network(G_copy1, "Network after 20% Degree-based Attack")
            visualize_network(G_copy2, "Network after 20% Clustering-based Attack")

    # Plot the results
    plt.plot(fractions_removed, largest_components_degree, label='Degree-based attack')
    plt.plot(fractions_removed, largest_components_clustering, label='Clustering-based attack')
    plt.xlabel('Fraction of nodes removed')
    plt.ylabel('Size of largest component')
    plt.legend()
    plt.title('Attack on Social Network: Degree vs Clustering Coefficient')
    plt.show()

# Example usage
N = 500  # Reduced for better visualization
gamma = 2.5
conspiracy_simulation(N, gamma)



"""## Avalanche"""

------------------------------------------------------------------
import random
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

# Avalanche simulation function with network visualization
def simulate_avalanches(G, num_steps=10000, grain_loss=1e-4, visualize_step=2000):
    # Initialize bucket sizes (equal to node degrees)
    bucket_sizes = {node: G.degree(node) for node in G.nodes()}
    sand_in_buckets = {node: 0 for node in G.nodes()}
    avalanche_sizes = []

    for step in range(num_steps):
        # Add a grain to a random node
        node = random.choice(list(G.nodes()))
        sand_in_buckets[node] += 1

        # Perform topplings
        avalanche_size = 0
        unstable_nodes = [node]

        while unstable_nodes:
            current_node = unstable_nodes.pop()
            if sand_in_buckets[current_node] >= bucket_sizes[current_node]:
                # Node topples
                avalanche_size += 1
                excess_grains = sand_in_buckets[current_node]
                sand_in_buckets[current_node] = 0  # Reset bucket

                # Distribute grains to neighbors
                for neighbor in G.neighbors(current_node):
                    sand_in_buckets[neighbor] += (1 - grain_loss)
                    if sand_in_buckets[neighbor] >= bucket_sizes[neighbor]:
                        unstable_nodes.append(neighbor)

        avalanche_sizes.append(avalanche_size)

        # Visualize the network at the specified step
        if step == visualize_step:
            visualize_network(G, sand_in_buckets, f"Network at Step {visualize_step} (Avalanche)")

    return avalanche_sizes

# Plot avalanche distribution
def plot_avalanche_distribution(avalanche_sizes, title):
    unique_sizes, counts = np.unique(avalanche_sizes, return_counts=True)
    probabilities = counts / np.sum(counts)

    plt.loglog(unique_sizes, probabilities, marker='o', linestyle='none')
    plt.xlabel('Avalanche Size (s)')
    plt.ylabel('P(s)')
    plt.title(title)
    plt.show()

# Generate random network (Erdős-Rényi)
def generate_erdos_renyi(N, avg_k):
    p = avg_k / (N - 1)
    G = nx.erdos_renyi_graph(N, p)
    return G

# Generate scale-free network
def generate_scale_free_network(N, gamma):
    # Generate a Zipf degree sequence
    degree_sequence = np.random.zipf(gamma, N)

    # Ensure that the sum of the degree sequence is even
    if sum(degree_sequence) % 2 != 0:
        # Adjust by adding 1 to a random node's degree
        degree_sequence[random.randint(0, N - 1)] += 1

    # Generate the configuration model graph
    G = nx.configuration_model(degree_sequence)
    G = nx.Graph(G)  # Convert to simple graph
    G.remove_edges_from(nx.selfloop_edges(G))  # Remove self-loops
    return G

# Visualize the network
def visualize_network(G, sand_in_buckets=None, title="Network Visualization"):
    plt.figure(figsize=(10, 10))
    pos = nx.spring_layout(G, seed=42)  # For consistent layout
    node_colors = 'blue'

    if sand_in_buckets:
        node_colors = [sand_in_buckets[node] for node in G.nodes()]
        nx.draw(G, pos, node_size=50, node_color=node_colors, cmap=plt.cm.Blues, with_labels=False)
    else:
        nx.draw(G, pos, node_size=50, node_color=node_colors, with_labels=False)

    plt.title(title)
    plt.show()

# Example usage for both types of networks
N = 500
avg_k = 2

# Erdős-Rényi network
G_er = generate_erdos_renyi(N, avg_k)
visualize_network(G_er, title="Erdős-Rényi Network (Before Avalanche)")
avalanche_sizes_er = simulate_avalanches(G_er, visualize_step=2000)
plot_avalanche_distribution(avalanche_sizes_er, "Avalanche Size Distribution (Erdős-Rényi)")

# Scale-free network (Configuration model)
G_sf = generate_scale_free_network(N, gamma=2.5)
visualize_network(G_sf, title="Scale-Free Network (Before Avalanche)")
avalanche_sizes_sf = simulate_avalanches(G_sf, visualize_step=2000)
plot_avalanche_distribution(avalanche_sizes_sf, "Avalanche Size Distribution (Scale-Free)")
-------------------------------------------------------------------------------------------
BA networks
---------------------

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import powerlaw

# Parameters
N = 10_000  # Total number of nodes
m = 4       # Number of edges to attach from a new node to existing nodes
intermediate_steps = [100, 1000]

# Generate Barabási-Albert network
def generate_ba_network(N, m):
    return nx.barabasi_albert_graph(N, m)

# Measure degree distribution
def degree_distribution(G):
    degrees = np.array(list(dict(G.degree()).values()))
    return np.bincount(degrees), degrees

# Plot degree distribution and fit power-law
def plot_degree_distribution(degree_counts, label):
    k = np.arange(len(degree_counts))
    plt.loglog(k, degree_counts, marker='o', linestyle='none', label=label)

    # Fit to power-law
    fit = powerlaw.Fit(k[degree_counts > 0], discrete=True)
    alpha = fit.alpha
    xmin = fit.xmin
    fit.plot_pdf()

    return alpha, xmin

# Plot cumulative degree distribution
def plot_cumulative_distribution(degree_counts, label):
    k = np.arange(len(degree_counts))
    cumulative_counts = np.cumsum(degree_counts[::-1])[::-1]
    plt.loglog(k, cumulative_counts, marker='o', linestyle='none', label=label)

# Measure average clustering coefficient
def average_clustering_coefficient(G):
    return nx.average_clustering(G)

# Visualize the network
def visualize_network(G, title):
    plt.figure(figsize=(8, 8))
    pos = nx.spring_layout(G)  # Use spring layout for a clean display
    nx.draw(G, pos, node_size=10, node_color="blue", edge_color="gray", alpha=0.7)
    plt.title(title)
    plt.show()

# Main analysis
degree_distributions = {}
clustering_coefficients = []

# Visualize the network at the start (using the first intermediate step)
initial_step = intermediate_steps[0]
initial_G = generate_ba_network(initial_step, m)
visualize_network(initial_G, f"Barabási-Albert Network (N = {initial_step}, m = {m})")

for t in intermediate_steps:
    G = generate_ba_network(t, m)
    degree_counts, _ = degree_distribution(G)
    degree_distributions[t] = degree_counts
    clustering_coeff = average_clustering_coefficient(G)
    clustering_coefficients.append(clustering_coeff)

# Plot degree distributions
plt.figure(figsize=(12, 6))
for t in intermediate_steps:
    plot_degree_distribution(degree_distributions[t], f'N = {t}')

plt.xlabel('Degree (k)')
plt.ylabel('P(k)')
plt.title('Degree Distribution of Barabási-Albert Network')
plt.legend()
plt.grid()
plt.show()

# Plot cumulative degree distributions
plt.figure(figsize=(12, 6))
for t in intermediate_steps:
    plot_cumulative_distribution(degree_distributions[t], f'N = {t}')

plt.xlabel('Degree (k)')
plt.ylabel('Cumulative P(k)')
plt.title('Cumulative Degree Distribution of Barabási-Albert Network')
plt.legend()
plt.grid()
plt.show()

# Plot average clustering coefficient vs N
plt.figure(figsize=(8, 5))
plt.plot(intermediate_steps, clustering_coefficients, marker='o')
plt.xlabel('Number of Nodes (N)')
plt.ylabel('Average Clustering Coefficient')
plt.title('Average Clustering Coefficient vs Number of Nodes')
plt.grid()
plt.show()
------------------------------------------------------------------

"""Calculate the degree exponent of the directed Barabási-Albert model with accelerated growth, assuming that the degree of the newly arriving
nodes increases in time as m(t) = t
Θ
"""

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from collections import Counter

# Function for power-law fitting
def power_law(x, gamma):
    return x ** (-gamma)

# Directed Barabási-Albert model with accelerated growth
def directed_ba_accelerated_growth(n, theta, m0=2):
    G = nx.DiGraph()
    # Initial small network of m0 nodes
    G.add_nodes_from(range(m0))
    for i in range(m0):
        for j in range(i):
            G.add_edge(i, j)

    # Growth with preferential attachment
    for t in range(m0, n):
        m_t = int(t**theta)  # Accelerated growth: m(t) = t^theta
        targets = _preferential_attachment(G, m_t)
        G.add_node(t)
        for target in targets:
            G.add_edge(t, target)

    return G

# Preferential attachment: choose nodes based on their in-degree
def _preferential_attachment(G, num_edges):
    degrees = np.array([G.in_degree(n) + 1 for n in G.nodes()])  # Add 1 to avoid zero probability
    probabilities = degrees / degrees.sum()
    targets = np.random.choice(G.nodes(), size=num_edges, replace=False, p=probabilities)
    return targets

# Plot degree distribution and fit power law
def plot_degree_distribution_and_fit(G, theta):
    in_degrees = [d for _, d in G.in_degree()]
    degree_count = Counter(in_degrees)
    degrees, counts = zip(*degree_count.items())

    plt.figure(figsize=(8, 6))
    plt.scatter(degrees, counts, color='blue', label='Degree Distribution')

    # Fit the degree distribution to a power-law
    popt, _ = curve_fit(power_law, degrees, counts)
    gamma = popt[0]
    print(f"Estimated Degree Exponent (gamma) for theta={theta}: {gamma:.2f}")

    # Plot fitted power-law
    fitted = power_law(np.array(degrees), gamma)
    plt.plot(degrees, fitted, color='red', linestyle='--', label=f'Fitted Power Law (gamma={gamma:.2f})')

    plt.xscale('log')
    plt.yscale('log')
    plt.xlabel('Degree (k)')
    plt.ylabel('Count')
    plt.title(f'Degree Distribution and Power-Law Fit (theta={theta})')
    plt.legend()
    plt.show()

# Main function to run the simulation and plot the results
def main():
    n = 1000  # Total number of nodes
    theta = 0.5  # Exponent controlling the accelerated growth, m(t) = t^theta

    G = directed_ba_accelerated_growth(n, theta)
    plot_degree_distribution_and_fit(G, theta)

if __name__ == "__main__":
    main()

"""Random Failure: Beyond Scale-Free Networks Calculate the critical threshold fc for networks with
a. Power law with exponential cutoff.
b. Lognormal distribution.
c. Delta distribution (all nodes have the same degree).
"""

import numpy as np
from scipy.integrate import quad
from scipy.stats import lognorm

# 1. Power Law with Exponential Cutoff
def power_law_exponential_cutoff(k, gamma, k_c):
    return k**(-gamma) * np.exp(-k/k_c)

def moments_power_law_exponential_cutoff(gamma, k_c, k_min=1):
    # First moment: <k>
    integrand_k = lambda k: k * power_law_exponential_cutoff(k, gamma, k_c)
    avg_k, _ = quad(integrand_k, k_min, np.inf)

    # Second moment: <k^2>
    integrand_k2 = lambda k: k**2 * power_law_exponential_cutoff(k, gamma, k_c)
    avg_k2, _ = quad(integrand_k2, k_min, np.inf)

    return avg_k, avg_k2

def critical_threshold_power_law(gamma, k_c):
    avg_k, avg_k2 = moments_power_law_exponential_cutoff(gamma, k_c)
    kappa = avg_k2 / avg_k
    fc = 1 - 1 / (kappa - 1)
    return fc

# 2. Lognormal Distribution
def moments_lognormal(mu, sigma):
    # First moment: <k>
    avg_k = np.exp(mu + 0.5 * sigma**2)

    # Second moment: <k^2>
    avg_k2 = np.exp(2 * mu + 2 * sigma**2)

    return avg_k, avg_k2

def critical_threshold_lognormal(mu, sigma):
    avg_k, avg_k2 = moments_lognormal(mu, sigma)
    kappa = avg_k2 / avg_k
    fc = 1 - 1 / (kappa - 1)
    return fc

# 3. Delta Distribution (All nodes have the same degree)
def critical_threshold_delta(k_0):
    kappa = k_0
    fc = 1 - 1 / (kappa - 1)
    return fc

# Main calculation
if __name__ == "__main__":
    # Power law with exponential cutoff
    gamma = 2.5  # Power-law exponent
    k_c = 10     # Exponential cutoff
    fc_power_law = critical_threshold_power_law(gamma, k_c)
    print(f"Critical threshold for Power Law with Exponential Cutoff: {fc_power_law:.4f}")

    # Lognormal distribution
    mu = 1       # Mean of the lognormal distribution
    sigma = 0.5  # Standard deviation of the lognormal distribution
    fc_lognormal = critical_threshold_lognormal(mu, sigma)
    print(f"Critical threshold for Lognormal Distribution: {fc_lognormal:.4f}")

    # Delta distribution (all nodes have the same degree)
    k_0 = 4      # Degree of all nodes
    fc_delta = critical_threshold_delta(k_0)
    print(f"Critical threshold for Delta Distribution: {fc_delta:.4f}")

import networkx as nx
import numpy as np
import matplotlib.pyplot as plt

# Function to generate a scale-free network using the configuration model
def generate_scale_free_network(n, degree_sequence):
    G = nx.configuration_model(degree_sequence)
    G = nx.Graph(G)  # Remove parallel edges
    G.remove_edges_from(nx.selfloop_edges(G))  # Remove self-loops
    return G

# Function to calculate the Molloy-Reed criterion
def molloy_reed_criterion(G):
    degrees = np.array([d for n, d in G.degree()])
    k1 = np.mean(degrees)
    k2 = np.mean(degrees ** 2)
    molloy_reed = k2 / k1
    return molloy_reed

# Function to calculate the critical threshold for random failures
def critical_threshold(G):
    degrees = np.array([d for n, d in G.degree()])
    k1 = np.mean(degrees)
    k2 = np.mean(degrees ** 2)

    # Critical threshold (random failures): p_c = 1 - 1 / (k2/k1 - 1)
    p_c = 1 - 1 / (k2 / k1 - 1)
    return p_c

# Function to remove nodes from the network based on the critical threshold
def remove_random_nodes(G, fraction):
    num_nodes_to_remove = int(fraction * G.number_of_nodes())
    nodes_to_remove = np.random.choice(G.nodes(), num_nodes_to_remove, replace=False)
    G.remove_nodes_from(nodes_to_remove)
    return G

# Function to check if the network is still connected (giant connected component)
def is_connected_after_removal(G):
    largest_cc = max(nx.connected_components(G), key=len)
    size_of_largest_cc = len(largest_cc)
    total_nodes = G.number_of_nodes()
    return size_of_largest_cc, total_nodes

# Example usage
n = 1000  # Number of nodes
gamma = 3  # Power-law exponent
degree_sequence = np.random.zipf(gamma, size=n)

# Make sure degree sequence has an even sum (necessary for configuration model)
if sum(degree_sequence) % 2 != 0:
    degree_sequence[0] += 1

# Generate the scale-free network
G = generate_scale_free_network(n, degree_sequence)

# Calculate the critical threshold
p_c = critical_threshold(G)
print(f"Critical Threshold (random failures): {p_c}")

# Remove nodes randomly according to the critical threshold fraction
G_after_removal = remove_random_nodes(G, p_c)

# Check if the network is still connected (size of the largest connected component)
size_of_largest_cc, total_nodes = is_connected_after_removal(G_after_removal)

print(f"Size of largest connected component after node removal: {size_of_largest_cc}")
print(f"Total nodes remaining: {total_nodes}")

if size_of_largest_cc < total_nodes / 2:
    print("The network is no longer connected (giant component has collapsed).")
else:
    print("The network remains connected (giant component is still intact).")

# Optional: Visualize the network after node removal
def plot_network(G, title):
    plt.figure(figsize=(5, 5))
    pos = nx.spring_layout(G)
    nx.draw(G, pos, node_size=10, with_labels=False)
    plt.title(title)
    plt.show()

# Plot the network after removal (optional)
plot_network(G_after_removal, "Scale-Free Network After Node Removal (Critical Threshold)")